"""empty message

Revision ID: 07ae267b64f7
Revises: 
Create Date: 2022-12-13 03:16:39.206259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ae267b64f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_model',
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('uid', sa.String(length=250), nullable=False),
    sa.Column('createdAt', sa.String(length=250), nullable=False),
    sa.Column('photoURL', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'createdAt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_model')
    # ### end Alembic commands ###
